name: Create release
on:
  push:
    branches: [main]

env:
  CI: true

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Output github ref
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
  build:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
            server-id: github
            settings-path: ${{ github.workspace }}

        #- name: Check if a release is needed
        #  id: release_check
        #  run: scripts/check_release
        #  env:
        #

        - name: Debug
          run: |
            echo "GITHUB_REF: $GITHUB_REF"
