name: Debug tags workflow
on:
  push:
    tags:
      - v[12].[0-9]+.[0-9]+

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Output github ref
        run: |
          echo "GITHUB_REF: $GITHUB_REF"

      - name: Only output on main branch
        if: ${{ always() && format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
        run: |
          echo "This ran because it is on the main branch"