name: Debug tags workflow
on:
  push:
    tags:
      - v[12].[0-9]+.[0-9]+

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Output github ref
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
